name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.TOKEN }}

    - name: Update package.json version
      run: |
        npm --no-git-tag-version version patch

    - name: Commit and push changes
        # git remote add origin https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
      run: |
        git config --local user.email "oscarkaka222@gmail.com"
        git config --local user.name "OscarSilvaOfficial"
        git add package.json
        git commit -m "Update package.json version"
        git push origin main

    # - name: Create Release
    #   if: contains('${{ github.head_ref }}', 'fix')
    #   run: |
    #     curl -H "Authorization: token ${{ secrets.TOKEN }}" -H "Content-Type: application/json" -X POST -d "{\"tag_name\": \"v${{ steps.get_version.outputs.version }}\", \"name\": \"Release v${{ steps.get_version.outputs.version }}\", \"body\": \"Release version ${{ steps.get_version.outputs.version }}\"}" https://api.github.com/repos/${{ github.repository }}/releases
