name: Release on merge

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Determine release type
      run: |
        if [[ "${{ steps.branch_name.outputs.branch_name }}" == *"fix"* ]]; then
          echo "::set-output name=release_type::bugfix"
        elif [[ "${{ steps.branch_name.outputs.branch_name }}" == *"feat"* ]]; then
          echo "::set-output name=release_type::minor"
        elif [[ "${{ steps.branch_name.outputs.branch_name }}" == *"release"* ]]; then
          echo "::set-output name=release_type::major"
        else
          echo "::set-output name=release_type::none"
      env:
        release_type: ${{ steps.determine_release_type.outputs.release_type }}
      
    - name: Generate release
      if: env.release_type != 'none'
      run: |
        echo "Creating a ${env.release_type} release"
        git tag -a v0.0.1 -m "Release v0.0.1"
        git push --tags
