name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Branch mergerd
      run: echo "Branch mergerd is ${{ github.head_ref }}"

    - name: Install semantic-release
      run: npm install -g semantic-release-cli

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: npx semantic-release

    # - name: Create Release
    #   if: contains('${{ github.head_ref }}', 'fix')
    #   run: |
    #     curl -H "Authorization: token ${{ secrets.TOKEN }}" -H "Content-Type: application/json" -X POST -d "{\"tag_name\": \"v${{ steps.get_version.outputs.version }}\", \"name\": \"Release v${{ steps.get_version.outputs.version }}\", \"body\": \"Release version ${{ steps.get_version.outputs.version }}\"}" https://api.github.com/repos/${{ github.repository }}/releases
