name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PR information
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER)
        BRANCH=$(echo $PR_INFO | jq -r .head.ref)
        echo "Merged branch: $BRANCH"

    - name: Log branch name
      shell: bash
      run: echo "Branch merged | $BRANCH"

    # - name: Create Release
    #   if: contains('${{ env.PROJECT_TO_TEST }}', 'SomeString')
    #   run: |
    #     curl -H "Authorization: token ${{ secrets.TOKEN }}" -H "Content-Type: application/json" -X POST -d "{\"tag_name\": \"v${{ steps.get_version.outputs.version }}\", \"name\": \"Release v${{ steps.get_version.outputs.version }}\", \"body\": \"Release version ${{ steps.get_version.outputs.version }}\"}" https://api.github.com/repos/${{ github.repository }}/releases
