name: Create Tag and Update Version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update version
      run: |
        version=$(cat package.json | jq -r '.version')
        major=$(echo $version | awk -F '.' '{print $1}')
        minor=$(echo $version | awk -F '.' '{print $2}')
        patch=$(echo $version | awk -F '.' '{print $3}')
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"
        echo $new_version > version.txt
        sed -i "
