name: Release on merge

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # - name: Get branch name
    #   run: echo "Branch name: $(basename ${GITHUB_REF#refs/heads/})"
    #   id: branch_name
      
    - name: Determine release type
      run: |
        if [[ "${{ steps.branch_name.outputs.branch_name }}" == *"fix"* ]]; then
          echo "::set-output name=release_type::bugfix"
        elif [[ "${{ steps.branch_name.outputs.branch_name }}" == *"feat"* ]]; then
          echo "::set-output name=release_type::minor"
        elif [[ "${{ steps.branch_name.outputs.branch_name }}" == *"release"* ]]; then
          echo "::set-output name=release_type::major"
        else
          echo "::set-
