name: Release on merge to main with word fix in branch

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use semantic-release
      run: npx semantic-release -E @semantic-release/exec
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NODE_ENV: production
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: 'Release v${{ env.TAG_NAME }}'
        draft: false
        prerelease: false
